# Use an official Python runtime as a parent image
FROM python:3.9-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install OpenSSH client, ping utility, and Flask
RUN apk update && \
    apk add --no-cache openssh-client iputils && \
    pip install --no-cache-dir Flask==2.3.3

# Disable strict host key checking for SSH
RUN mkdir -p /root/.ssh && \
    echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config

# Define environment variable
ENV FLASK_APP=app.py

# Run the Flask app
CMD ["flask", "run", "--host=0.0.0.0"]
